SELECT A.CAR_ID
    , A.CAR_TYPE
    , A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100) * 30 AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_ID NOT IN (SELECT CAR_ID
                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                           WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-11-30'
                           AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01'
                          )
      AND CAR_TYPE IN ('세단', 'SUV')
     ) A , CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
WHERE A.CAR_TYPE = B.CAR_TYPE
AND B.DURATION_TYPE LIKE '30일%'
AND A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100) * 30 BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC

