-- HAVING은 집계 함수를 사용하여 조건을 줄 수 있다.
-- 날짜 +1 명심하기.
SELECT CAR_ID, ROUND(AVG(END_DATE-START_DATE+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID 
HAVING ROUND(AVG(END_DATE-START_DATE+1), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC