SELECT A.USER_ID, A.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER A, USED_GOODS_BOARD B
WHERE A.USER_ID = B.WRITER_ID
AND B.STATUS LIKE 'DONE'
HAVING SUM(B.PRICE) >= 700000
GROUP BY A.USER_ID, A.NICKNAME
ORDER BY TOTAL_SALES