SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH
    , CAR_ID
    , COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE EXTRACT(MONTH FROM START_DATE) IN (8, 9, 10)
                 GROUP BY CAR_ID
                 HAVING COUNT(*) > 4
                )
AND TO_CHAR(START_DATE, 'MM') BETWEEN 8 AND 10
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
ORDER BY MONTH, CAR_ID DESC