/*
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_ID = B.CAR_ID
AND TO_CHAR(B.START_DATE, 'MM') = '10'
AND A.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC;
*/
-- ON과 WHERE을 헷갈리지 말기
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A 
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE TO_CHAR(B.START_DATE, 'MM') = '10'
AND A.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC