-- AND A.AUTHOR_ID = B.AUTHOR_ID 이런 조건 빼먹지 말기
SELECT A.BOOK_ID, B.AUTHOR_NAME, TO_CHAR(A.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK A, AUTHOR B
WHERE A.CATEGORY LIKE '경제'
AND A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE